## @Api_HostAddress = http://localhost:5288
@Api_HostAddress = https://localhost:7187


### ####################################
### Get a Welcome message
Get  {{Api_HostAddress}}/api


### ERROR no URL

POST  {{Api_HostAddress}}/api/UrlCreate
Accept: application/json
Content-Type: application/json

{
	"Vanity": "1111-test",
	"Url": "",
	"Title": ".NET Aspire Azure Blob Storage integration"
}

### ERROR URL not valid

POST  {{Api_HostAddress}}/api/UrlCreate
Accept: application/json
Content-Type: application/json

{
	"Vanity": "1111-test",
	"Url": "That's not a URL",
	"Title": ".NET Aspire Azure Blob Storage integration"
}

### ####################################
### Create a new short URL

POST  {{Api_HostAddress}}/api/UrlCreate
Accept: application/json
Content-Type: application/json

{
	"Vanity": "1111-test",
	"Url": "https://learn.microsoft.com/en-us/dotnet/aspire/storage/azure-storage-blobs-integration?tabs=dotnet-cli",
	"Title": ".NET Aspire Azure Blob Storage integration"
}

### ####################################
### Get list of URLs

GET  {{Api_HostAddress}}/api/UrlList
Accept: application/json



### ####################################
### Update existing URL

POST  {{Api_HostAddress}}/api/UrlUpdate
Accept: application/json
Content-Type: application/json

{
	"partitionKey": "1",
    "rowKey": "1111-test",
	"Vanity": "1111-test",
	"Url": "https://learn.microsoft.com",
	"Title": "Microsoft Learn",
	"Archived": false
}



### ####################################
### Archive a new short URL

POST  {{Api_HostAddress}}/api/UrlArchive
Accept: application/json
Content-Type: application/json

{
	"partitionKey": "1",
    "rowKey": "1111-test",
	"Vanity": "1111-test",
	"Url": "https://learn.microsoft.com/en-us/dotnet/aspire/storage/azure-storage-blobs-integration?tabs=dotnet-cli",
	"Title": ".NET Aspire Azure Blob Storage integration"
}




### ####################################
### Get Stats

POST  {{Api_HostAddress}}/api/UrlClickStatsByDay
Accept: application/json
Content-Type: application/json

{
	"Vanity": "1111-test"
}


### ####################################
### Get All Stats

POST  {{Api_HostAddress}}/api/UrlClickStatsByDay
Accept: application/json
Content-Type: application/json

{}




### ####################################
### Create a new short URL no Vanity

POST  {{Api_HostAddress}}/api/UrlCreate
Accept: application/json
Content-Type: application/json

{
	"Url": "https://learn.microsoft.com",
	"Title": "Microsoft Learn"
}



### ####################################
### Create a new short URL

POST  {{Api_HostAddress}}/api/UrlCreate
Accept: application/json
Content-Type: application/json

{
	"Vanity": "blazor",
	"Url": "https://www.fluentui-blazor.net/",
	"Title": "Fluent UI Blazor library"
}


### ####################################
### Generate Clicks

POST  {{Api_HostAddress}}/api/GenerateClicks
Accept: application/json
Content-Type: application/json

{
	"Vanity": "blazor"
}